site_name: 501st Aux mod Mkdocs


nav:
    - Home: index.md
    - About us: aboutus.md
    - Helmet Information: helmets.md
    - Current Projects: current_projects.md
    - Changelogs:
        Changelog Information: changelog.md
        Legacy Changelogs:
          1. RE3: changelogs/legacy_changelogs/RE3.md
          2. Airerium: changelogs/legacy_changelogs/aireium.md
         

theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
    icon: 'whatshot'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'blue'
    accent: 'amber'

markdown_extensions:
  - toc
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark

plugins:
  - search


extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
